### ISSUE TITLE
Синтаксической ошибке в данном примере нет

### ISSUE THREAD

**Issue by andrey-ilyin** [vladislav-gavrilin/web#2]
https://github.com/vladislav-gavrilin/web/blob/f48b8c63cb55586e789dadab99e1e862db48864e/lab1/lab1.txt#L22

**Comment by vladislav-gavrilin** [comment]
Исправлено задание 2.d 
HTTP ERROR 400(Failed to load resource: the server responded with a status of 400 (Work hard!)) - эта ошибка означает, что пользователь (его браузер) отправил неправильный запрос на сервер где расположен сайт.
Решение: Необходимо заменить hardly на hard и выполнить запрос http://localhost/lw1/javascript_is_a_client_side_language.php?how_to_work=hard

**Comment by andrey-ilyin** [comment]
Принято.
